description: Iowa allows these deductions against net income to reach taxable income.
values:
  2021-01-01:
    - ia_fedtax_deduction  # deduction of selected federal taxes
    - ia_qbi_deduction  # deduction of a fraction of federal QBID
    - ia_basic_deduction  # deduction of Iowa standard or itemized deductions
  2024-01-01:
    - ia_qbi_deduction  # deduction of a fraction of federal QBID
    - ia_basic_deduction  # deduction of Iowa standard or itemized deductions

metadata:
  unit: list
  label: Iowa deductions against net income to reach taxable income
  reference:
  - title: 2021 IA1040 Iowa Income Tax Return, Lines 28, 31, 32, 37
    href: https://tax.iowa.gov/sites/default/files/2022-01/IA1040%2841-001%29.pdf#page=1
  - title: 2021 IA1040 Income Tax Return instructions
    href: https://tax.iowa.gov/sites/default/files/2023-01/2021%20Expanded%20Instructions_010323.pdf#page=40
  - title: 2022 IA1040 Iowa Income Tax Return, Lines 28, 31, 32, 37
    href: https://tax.iowa.gov/sites/default/files/2023-01/2022IA1040%2841001%29.pdf#page=1
  - title: 2022 IA1040 Income Tax Return instructions
    href: https://tax.iowa.gov/sites/default/files/2023-03/2022%20Expanded%20Instructions_022023.pdf#page=38
  - title: 2024 IA1040 Iowa Income Tax Return Instruction
    href: https://revenue.iowa.gov/media/4152/download?inline#page=61
