description: Georgia provides military retirement income exclusion for the age filer at this amount.
metadata:
  label: Georgia military retirement income exclusion base amount
  period: year
  unit: currency-USD
  reference: 
  # Georgia military exclusion was introduced in 2022
  - title: 2022 IT-511 Individual Income Tax Booklet - Subtractions(2)
    href: https://dor.georgia.gov/document/document/2022-it-511-individual-income-tax-booklet/download#page=16
  - title: 2023 IT-511 Individual Income Tax Booklet - Subtractions(2)
    href: https://dor.georgia.gov/document/document/2023-it-511-individual-income-tax-booklet/download#page=16
  - title: Official Code of Georgia Annotated | CH17 Income Taxes | O.C.G.A. ยง 48-7-27 | (a)-(5.1)
    href: https://advance.lexis.com/documentpage/?pdmfid=1000516&crid=fb5db531-a80f-4790-bddb-eefc8327ef60&config=00JAA1MDBlYzczZi1lYjFlLTQxMTgtYWE3OS02YTgyOGM2NWJlMDYKAFBvZENhdGFsb2feed0oM9qoQOMCSJFX5qkd&pddocfullpath=%2Fshared%2Fdocument%2Fstatutes-legislation%2Furn%3AcontentItem%3A65D2-CDH3-CGX8-044N-00008-00&pdcontentcomponentid=234186&pdteaserkey=sr1&pditab=allpods&ecomp=8s65kkk&earg=sr1&prid=66f02b0a-c5ae-4162-9535-127751546807
values:
  2022-01-01: 17_500
