description: Maine provides this sales tax fairness credit base amount to filers, based on the filing status.
SINGLE:
  values:
    2021-01-01: 130
    2023-01-01: 140
    2024-01-01: 150
  uprating:
    parameter: gov.irs.uprating
    rounding:
      type: downwards
      interval: 5
JOINT:
  values:
    2021-01-01: 180
    2022-01-01: 185
    2023-01-01: 200
    2024-01-01: 210
  uprating:
    parameter: gov.irs.uprating
    rounding:
      type: downwards
      interval: 5
SEPARATE:
  values:
    2021-01-01: 0
  uprating:
    parameter: gov.irs.uprating
    rounding:
      type: downwards
      interval: 5
HEAD_OF_HOUSEHOLD:
  values:
    2021-01-01: 180
    2022-01-01: 185
    2023-01-01: 200
    2024-01-01: 210
  uprating:
    parameter: gov.irs.uprating
    rounding:
      type: downwards
      interval: 5
SURVIVING_SPOUSE:
  values:
    2021-01-01: 180
    2022-01-01: 185
    2023-01-01: 200
    2024-01-01: 210
  uprating:
    parameter: gov.irs.uprating
    rounding:
      type: downwards
      interval: 5

metadata:
  unit: currency-USD
  reference:
    # Legal specifies inflation unadjusted amounts
    - title: ยง5213-A. Sales tax fairness credit (A-1) 
      href: https://legislature.maine.gov/statutes/36/title36sec5213-A.html
    - title: ยง5403. Annual adjustments for inflation 5(A)
      href: https://legislature.maine.gov/statutes/36/title36sec5403.html
    - title: 2021 Form 1040ME Property Tax Fairness Credit / Sales Tax Fairness Credit 
      href: https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/21_1040me_sched_pstfc_dwnldff.pdf#page=4
    - title: 2022 Form 1040ME Property Tax Fairness Credit / Sales Tax Fairness Credit 
      href: https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/22_1040me_sched_pstfc_ff.pdf#page=4
    - title: 2023 Form 1040ME Property Tax Fairness Credit / Sales Tax Fairness Credit
      href: https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/23_1040me_sched_pstfc_ff.pdf#page=4
    - title: 2024 Form 1040ME Property Tax Fairness Credit / Sales Tax Fairness Credit
      href: https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/23_1040me_sched_pstfc_ff.pdf#page=4
  period: year
  label: Maine sales tax fairness credit base amount
  breakdown:
  - filing_status
