description: The District of Columbia counts these income sources as countable income under the Child Care Subsidy Program.
values:
  2020-01-01:
    - employment_income
    - self_employment_income
    - dividend_income
    - interest_income 
    - rental_income
    - pension_income
    - veterans_benefits
    - military_retirement_pay
    - alimony_income
    # The following are exempted income
    # DC_TANF, SNAP, WIC, DC_LIHEAP, CHIP
    # social_security, ssi
    # disability_benefits
    # unemployment_compensation
    # child_support_received
    # eitc
    # capital_gains


metadata:
  unit: list
  period: year
  label: DC CCSP countable income sources
  reference:
    - title: DC Child Care Subsidy Program Policy Manual
      href: https://osse.dc.gov/sites/default/files/dc/sites/osse/publication/attachments/DC%20Child%20Care%20Subsidy%20Program%20Policy%20Manual.pdf#page=12
