description: The IRS includes this portion of Social Security benefits in taxable income for filers whose modified adjusted gross income is between the base and additional thresholds.
values:
  2013-01-01: 0.5

metadata:
  breakdown: filing_status
  unit: /1
  label: Social Security benefit base taxable rate
  reference: 
    - title: 26 U.S. Code ยง 86(a)(1)
      href: https://www.law.cornell.edu/uscode/text/26/86#a_1 
