description: Virginia multiplies the number of personal exemptions by this amount under the low income tax credit. 
values:
  2021-01-01: 300

metadata:
  period: year
  unit: currency-USD
  label: Virginia earned income tax credit low income credit base
  reference:
  - title: Code of Virginia ยง 58.1-339.8.B.1
    href: https://law.lis.virginia.gov/vacode/title58.1/chapter3/section58.1-339.8/
  - title: Virginia 2024 Form 760 Resident Individual Income Tax Booklet
    href: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2024-760-instructions.pdf#page=31
  - title: Virginia 2023 Form 760 Resident Individual Income Tax Booklet
    href: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2023-760-instructions.pdf#page=31
  - title: Virginia 2022 Form 760 Resident Individual Income Tax Booklet
    href: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2022-760-instructions.pdf#page=32
  - title: Virginia 2021 Form 760 Resident Individual Income Tax Booklet
    href: https://www.tax.virginia.gov/sites/default/files/vatax-pdf/2021-760-instructions.pdf#page=32
