description: Wisconsin homestead credit recognizes these income sources.
metadata:
  unit: variable
  label: Wisconsin homestead credit income sources
  reference:
    - title: Homestead Tax Credit, Wisconsin Legislative Fiscal Bureau
      href: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=14
values:
  2021-01-01:
    - adjusted_gross_income
    # additional homestead income sources:
    - tax_exempt_interest_income
    - tax_exempt_social_security
    - tax_exempt_pension_income
    - tax_exempt_unemployment_compensation
    # cash transfer income sources:
    - ssi
    - state_supplement
    - tanf
