description: Puerto Rico deductions from taxable income.
values:
  2023-01-01:
    - pr_casualty_loss_deduction
    - pr_charitable_deduction
    - pr_medical_expense_deduction
    - pr_mortgage_deduction
    - pr_education_deduction
    - pr_retirement_deduction
metadata:
  unit: list
  period: year
  label: Puerto Rico income deductions
  reference:
    - title: P.R. Laws tit. 13, ยง 30135 
      href: https://law.justia.com/codes/puerto-rico/title-thirteen/subtitle-17/part-ii/chapter-1005/subchapter-c/30135/
    - title: Gov. of Puerto Rico Individual Income Tax Return Form 482.0 4
      href: https://hacienda.pr.gov/sites/default/files/individuals_2024_rev._jul_12_24_9-30-24_informative.pdf#page=4
