description: Alaska provides this amount as the base payment under the Alaska Temporary Assistance Program for child-only cases with one dependent child.

values:
  2021-01-01: 452

metadata:
  unit: currency-USD
  period: month
  label: Alaska ATAP child-only base payment amount
  reference:
    - title: 7 AAC 45.523 - Maximum payment levels
      href: https://www.law.cornell.edu/regulations/alaska/7-AAC-45.523
