description: The California Department of Social Services provides the following base Infant Supplement amount. 
values:
  2022-01-01: 900
metadata:
  unit: currency-USD
  period: month
  label: California Department of Social Services Infant Supplement base amount
  reference:
    - title: California Department of Social Services ALL COUNTY LETTER NO. 21-123
      href: https://cdss.ca.gov/Portals/9/Additional-Resources/Letters-and-Notices/ACLs/2021/21-123.pdf?ver=2021-10-08-140950-570
    - title: Los Angeles County Department of Children and Family Services Teen Parenting
      href: https://dcfs.lacounty.gov/youth/teen-parenting/
