description: Illinois counts these income sources as countable income under the Child Care Assistance Program.
values:
  2020-01-01:
    - employment_income
    - self_employment_income
    - rental_income
    - dividend_income
    - interest_income
    - pension_income
    - veterans_benefits
    - unemployment_compensation
    # - capital_gains exempted
    # - snap exempted
    # - child_support_received exempted
    # - alimony_income exempted
    # - social_security exempted
    # - pension_survivors exempted
    # - railroad_benefits exempted

metadata:
  unit: list
  period: year
  label: Illinois CCAP countable income sources
  reference:
    - title: Ill. Admin. Code tit. 89, ยง 50.235 - Income Eligibility Criteria
      href: https://www.law.cornell.edu/regulations/illinois/Ill-Admin-Code-tit-89-SS-50.235
