from policyengine_us.model_api import *


MO_CSFP_COUNTIES = [
    "ADAIR_COUNTY_MO",
    "AUDRAIN_COUNTY_MO",
    "BARRY_COUNTY_MO",
    "BARTON_COUNTY_MO",
    "BATES_COUNTY_MO",
    "BENTON_COUNTY_MO",
    "BOLLINGER_COUNTY_MO",
    "BOONE_COUNTY_MO",
    "BUTLER_COUNTY_MO",
    "CALLAWAY_COUNTY_MO",
    "CAMDEN_COUNTY_MO",
    "CAPE_GIRARDEAU_COUNTY_MO",
    "CARROLL_COUNTY_MO",
    "CARTER_COUNTY_MO",
    "CASS_COUNTY_MO",
    "CEDAR_COUNTY_MO",
    "CHARITON_COUNTY_MO",
    "CHRISTIAN_COUNTY_MO",
    "CLARK_COUNTY_MO",
    "CLAY_COUNTY_MO",
    "CLINTON_COUNTY_MO",
    "COLE_COUNTY_MO",
    "COOPER_COUNTY_MO",
    "CRAWFORD_COUNTY_MO",
    "DADE_COUNTY_MO",
    "DALLAS_COUNTY_MO",
    "DENT_COUNTY_MO",
    "DOUGLAS_COUNTY_MO",
    "DUNKLIN_COUNTY_MO",
    "FRANKLIN_COUNTY_MO",
    "GASCONADE_COUNTY_MO",
    "GREENE_COUNTY_MO",
    "HENRY_COUNTY_MO",
    "HICKORY_COUNTY_MO",
    "HOWARD_COUNTY_MO",
    "HOWELL_COUNTY_MO",
    "IRON_COUNTY_MO",
    "JACKSON_COUNTY_MO",
    "JASPER_COUNTY_MO",
    "JEFFERSON_COUNTY_MO",
    "JOHNSON_COUNTY_MO",
    "KNOX_COUNTY_MO",
    "LACLEDE_COUNTY_MO",
    "LAFAYETTE_COUNTY_MO",
    "LAWRENCE_COUNTY_MO",
    "LEWIS_COUNTY_MO",
    "LINN_COUNTY_MO",
    "MACON_COUNTY_MO",
    "MADISON_COUNTY_MO",
    "MARIES_COUNTY_MO",
    "MARION_COUNTY_MO",
    "MCDONALD_COUNTY_MO",
    "MILLER_COUNTY_MO",
    "MISSISSIPPI_COUNTY_MO",
    "MONITEAU_COUNTY_MO",
    "MONROE_COUNTY_MO",
    "MONTGOMERY_COUNTY_MO",
    "MORGAN_COUNTY_MO",
    "NEW_MADRID_COUNTY_MO",
    "NEWTON_COUNTY_MO",
    "OREGON_COUNTY_MO",
    "OSAGE_COUNTY_MO",
    "OZARK_COUNTY_MO",
    "PEMISCOT_COUNTY_MO",
    "PERRY_COUNTY_MO",
    "PETTIS_COUNTY_MO",
    "PHELPS_COUNTY_MO",
    "PIKE_COUNTY_MO",
    "PLATTE_COUNTY_MO",
    "POLK_COUNTY_MO",
    "PULASKI_COUNTY_MO",
    "PUTNAM_COUNTY_MO",
    "RALLS_COUNTY_MO",
    "RANDOLPH_COUNTY_MO",
    "RAY_COUNTY_MO",
    "REYNOLDS_COUNTY_MO",
    "RIPLEY_COUNTY_MO",
    "SALINE_COUNTY_MO",
    "SCHUYLER_COUNTY_MO",
    "SCOTLAND_COUNTY_MO",
    "SCOTT_COUNTY_MO",
    "SHANNON_COUNTY_MO",
    "SHELBY_COUNTY_MO",
    "ST_CHARLES_COUNTY_MO",
    "ST_CLAIR_COUNTY_MO",
    "ST_FRANCOIS_COUNTY_MO",
    "ST_LOUIS_COUNTY_MO",
    "ST_LOUIS_CITY_MO",
    "STE_GENEVIEVE_COUNTY_MO",
    "STODDARD_COUNTY_MO",
    "STONE_COUNTY_MO",
    "SULLIVAN_COUNTY_MO",
    "TANEY_COUNTY_MO",
    "TEXAS_COUNTY_MO",
    "VERNON_COUNTY_MO",
    "WARREN_COUNTY_MO",
    "WASHINGTON_COUNTY_MO",
    "WAYNE_COUNTY_MO",
    "WEBSTER_COUNTY_MO",
    "WRIGHT_COUNTY_MO",
]


class mo_dhss_csfp_county_eligible(Variable):
    value_type = bool
    entity = Household
    definition_period = YEAR
    label = "Missouri DHSS CSFP county eligible"
    defined_for = StateCode.MO
    reference = (
        "https://health.mo.gov/living/wellness/nutrition/foodprograms/csfp/",
        "https://health.mo.gov/living/wellness/nutrition/foodprograms/csfp/pdf/missouri-state-plan-ada.pdf",
        "https://www.arcgis.com/home/item.html?id=d8d8553132194b2ebd038d171503e16c",
        "https://gis.mo.gov/arcgis/rest/services/DHSS/commodityFood/MapServer/0",
    )

    def formula(household, period, parameters):
        county = household("county_str", period)
        return np.isin(county, MO_CSFP_COUNTIES)
