description: Wisconsin adds these variables to US adjusted gross income when computing its gross income.
values:
  2021-01-01:
    - tax_exempt_interest_income
    - wi_capital_gain_loss_addition
    - form_4972_lumpsum_distributions

metadata:
  unit: list
  label: WI additions to US adjusted gross income
  reference:
  - title: 2021 WI schedule AD
    href: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleADf.pdf
  - title: 2021 WI schedule AD instructions
    href: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleAD-Inst.pdf
  - title: 2022 WI schedule AD
    href: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleADf.pdf
  - title: 2022 WI schedule AD instructions
    href: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleAD-Inst.pdf
  - title: 2023 WI schedule AD instructions
    href: https://www.revenue.wi.gov/TaxForms2023/2023-ScheduleAD-Inst.pdf
  - title: 2024 WI schedule AD instructions
    href: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleAD-Inst.pdf
