description: Income sources eligible for the South Carolina retirement deduction.
values:
  2021-01-01:
    - taxable_pension_income
    - taxable_retirement_distributions
metadata:
  unit: /1
  reference:
    - title: SC Code Section 12-6-1170(A)(1)
      href: https://www.scstatehouse.gov/code/t12c006.php
