description: Massachusetts counts these income sources as countable income under the Child Care Financial Assistance program.
values:
  2020-01-01:
    - employment_income_before_lsr
    - self_employment_income_before_lsr
    - dividend_income
    - interest_income
    - rental_income
    - pension_income
    - veterans_benefits
    - military_retirement_pay
    - alimony_income
    - child_support_received
    - social_security
    - ssi
    - unemployment_compensation
    - workers_compensation
    # The following are exempted income
    # ma_liheap, SNAP, ma_eaedc, ma_tafdc
    # disability_benefits
    # capital_gains


metadata:
  unit: list
  period: year
  label: Massachusetts CCFA countable income sources
  reference:
    - title: Massachusetts CCFA Policy Manual
      href: https://www.mass.gov/doc/eecs-financial-assistance-policy-guide-february-1-2022/download#page=37
