description: Idaho provides this amount under the grocery tax credit.
values:
  2015-01-01: 100
  2023-01-01: 120
metadata:
  label: Idaho grocery credit amount
  unit: currency-USD
  period: year
  reference:
    - title: 2022 Idaho Code Title 63 - REVENUE AND TAXATION Chapter 30 - INCOME TAX Section 63-3024A - FOOD TAX CREDITS AND REFUNDS
      href: https://law.justia.com/codes/idaho/2022/title-63/chapter-30/section-63-3024a/  
    - title: Form 40 Individual Income Tax Return - Line 43 - Grocery Credit
      href: https://tax.idaho.gov/wp-content/uploads/forms/EFO00089/EFO00089_12-30-2022.pdf#page=7
    - title: Form 24 Grocery Credit Refund 2022
      href: https://tax.idaho.gov/wp-content/uploads/forms/EFO00086/EFO00086_12-30-2022.pdf#page=1
    - title: Form 24 Grocery Credit Refund 2021
      href: https://tax.idaho.gov/wp-content/uploads/forms/EFO00086/EFO00086_09-15-2021.pdf#page=1
