description: Pennsylvania starts reducing its tax forgiveness when eligibility income exceeds this amount, or double for joint filers.
values:
  2004-01-01: 6_500
metadata:
  unit: currency-USD
  period: year
  name: pa_tax_forgiveness_base_rate
  label: PA base eligibility income
  reference:
    - title: PA PIT Guide - Chapter 20, Tax Forgiveness, page 15
      href: https://woodacctservices.com/publications/PA%20Income%20Tax%20Forgiveness%20Chart.pdf#page15
    - title: PA Form PA-40 Instructions, page 39
      href: https://www.revenue.pa.gov/FormsandPublications/FormsforIndividuals/PIT/Documents/2021/2021_pa-40in.pdf#page=39
    - title: 2024 Pennsylvania Personal Income Tax Return Instructions (PA-40 IN), PA SCHEDULE SP (LINE 21), Section III
      href: https://www.pa.gov/content/dam/copapwp-pagov/en/revenue/documents/formsandpublications/formsforindividuals/pit/documents/2024/2024_pa-40in.pdf#page=39
