description: Self-employment Social Security tax rate
values:
  2013-01-01: 0.124
metadata:
  unit: /1
  label: Self-employment Social Security tax rate
  reference:
    - title: 26 U.S. Code ยง 1401 - Rate of tax
      href: https://www.law.cornell.edu/uscode/text/26/1401#a
