description: California counts the following resources under the CalWORKs program.

metadata:
  unit: list
  period: year
  label: California CalWORKs TANF resources
  reference:
    - title: Los Angeles Department of Public Social Services E-Policy | Property Definitions
      href: http://epolicy.dpss.lacounty.gopv/epolicy/epolicy/server/general/projects_responsive/ePolicyMaster/index.htm?&area=general&type=responsivehelp&ctxid=&project=ePolicyMaster#t=mergedProjects%2FCalWORKs%2FCalWORKs%2F42-200_Property%2F42-200_Property.htm%23Definitionsbc-4&rhtocid=_3_1_2_0_3
values:
  2022-07-01:
    - assessed_property_value # real_property
    - spm_unit_cash_assets # personal_property
