description: Kansas provides the following exemption amount for disabled veterans.
values:
  2023-01-01: 2_250

metadata:
  period: year
  unit: currency-USD
  label: Kansas disabled veteran exemption amount
  reference:
  - title: 2023 Form K-40 instructions
    href: https://www.ksrevenue.gov/pdf/ip23.pdf#page=6
  - title: 2023 Form K-40 
    href: https://www.ksrevenue.gov/pdf/k-4023.pdf#page=2
  - title: 2024 Form K-40 instructions
    href: https://www.ksrevenue.gov/pdf/ip24.pdf#page=2
  - title: KS Stat ยง 79-32,121 (2023) (b)
    href: https://law.justia.com/codes/kansas/chapter-79/article-32/section-79-32-121/
