description: Puerto Rico accounts for the following exemption sources.
values:
  2024-01-01:
    - pr_personal_exemption
    - pr_dependents_exemption
    - pr_veteran_exemption
metadata:
  unit: list
  period: year
  label: Puerto Rico exemption sources
  reference:
    - title: P.R. Laws tit. 13, ยง 30138
      href: https://law.justia.com/codes/puerto-rico/title-thirteen/subtitle-17/part-ii/chapter-1005/subchapter-c/30138/
    - title: P.R. Individual Income Tax Return, Form 482
      href: https://hacienda.pr.gov/sites/default/files/individuals_2024_rev._jul_12_24_9-30-24_informative.pdf#page=2
