description: Puerto Rico exemptions from taxable income.
values:
  2023-01-01:
    - pr_personal_exemption
    - pr_veteran_exemption
    - pr_dependents_exemption
metadata:
  unit: list
  period: year
  label: Puerto Rico income exemptions
