description: Pennsylvania limits its TANF grant standard to households with up to this income level, by household size.
metadata:
  type: single_amount
  period: year
  threshold_unit: person
  amount_unit: currency-USD
  label: Pennsylvania TANF monthly income limit
  reference:
    - title: Pennsylvania State Cash Assistance for Number of Persons in Budget Group
      href: https://www.compass.state.pa.us/compass.web/menuitems/CashFAQ.aspx?Language=EN
brackets:
  - threshold:
      2021-01-01: 0
    amount:
      2021-01-01: 0
  - threshold:
      2021-01-01: 1
    amount:
      2021-01-01: #205 * 12
  - threshold:
      2021-01-01: 2
    amount:
      2021-01-01: #316 * 12
  - threshold:
      2021-01-01: 3
    amount:
      2021-01-01: #403 * 12
  - threshold:
      2021-01-01: 4
    amount:
      2021-01-01: #403 * 12
  - threshold:
      2021-01-01: 5
    amount:
      2021-01-01: #589 * 12
  - threshold:
      2021-01-01: 6
    amount:
      2021-01-01: #670 * 12

# change to year same as ad. person yaml
# find dates for values (all) - use 2022-01-01 for all
