description: Arizona limits income to this share of the federal poverty guideline under the Temporary Assistance for Needy Families program.

metadata:
  unit: /1
  period: year
  label: Arizona TANF income limit rate
  reference:
    - title: Arizona DES - Cash Assistance Income Eligibility Guidelines
      href: https://des.az.gov/services/child-and-family/cash-assistance/income-eligibility-guidelines
    - title: 2023 Arizona TANF State Plan
      href: https://des.az.gov/sites/default/files/dl/tanf_state_plan_oct_2023.pdf#page=18

values:
  1997-01-01: 1
