description: The IRS provides a maximum Child Tax Credit of this amount with an additional bracket, depending on the child's age.

brackets:
  - threshold:
      2013-01-01: 0
    amount:
      2013-01-01: 0
  - threshold:
      2013-01-01: 6
    amount:
      2013-01-01: 0
  - threshold:
      2013-01-01: 17
    amount:
      2013-01-01: 0
metadata:
  type: single_amount
  threshold_unit: year
  amount_unit: currency-USD
  amount_period: year
  label: Child Tax Credit amount
