description: Pennsylvania limits its TANF eligibility to households with income below this amount, depending on household size.
metadata:
  label: Pennsylvania TANF monthly income limit
  type: single_amount
  threshold_unit: person
  amount_unit: currency-USD
  period: year
  reference:
    - title: Pennsylvania State Cash Assistance for Number of Persons in Budget Group
      href: https://www.compass.state.pa.us/compass.web/menuitems/CashFAQ.aspx?Language=EN
brackets:
  - threshold:
      2022-01-01: 0
    amount:
      2022-01-01: 0
  - threshold:
      2022-01-01: 1
    amount:
      2022-01-01: 2_460
  - threshold:
      2022-01-01: 2
    amount:
      2022-01-01: 3_792
  - threshold:
      2022-01-01: 3
    amount:
      2022-01-01: 4_836
  - threshold:
      2022-01-01: 4
    amount:
      2022-01-01: 5_964
  - threshold:
      2022-01-01: 5
    amount:
      2022-01-01: 7_068
  - threshold:
      2022-01-01: 6
    amount:
      2022-01-01: 8_040
