description: New Hampshire provides this base exemption based on filing status.
metadata:
  unit: currency-USD
  period: year
  breakdown:
  - filing_status
  label: New Hampshire base exemption amount
  reference: 
    - title: TECHNICAL INFORMATION RELEASE TIR 2025-001 I&D Tax Repealed Effective January 1, 2025
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/2025-001-technical-information-release-repeal.pdf
    - title: TITLE V - TAXATION - CHAPTER 77 - TAXATION OF INCOMES - Section 77:5
      href: https://www.gencourt.state.nh.us/rsa/html/V/77/77-5.htm
    - title: 2024 New Hampshire DP-10 Form Instructions
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-instructions-2024.pdf#page=6
    - title: 2023 DP-10 Interest and Dividends Tax Return Instructions
      href: https://www.revenue.nh.gov/forms/2024/documents/dp-10-instructions-2023.pdf#page=6
    - title: 2022 DP-10 Interest and Dividends Tax Return Instructions
      href: https://www.revenue.nh.gov/forms/2023/documents/dp-10-instructions-2022.pdf#page=4
    # NH DRA forms available from 2017-2023
    - title: 2023 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-2023_pro.pdf#page=3
    - title: 2022 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-2022-print.pdf#page=3
    - title: 2021 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-2021-print.pdf#page=3
    - title: 2020 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-2020-print.pdf#page=3
    - title: 2019 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-2019-print.pdf#page=3
    - title: 2018 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-2018-print.pdf#page=3
    - title: 2017 New Hampshire DP-10 Form (Line 6 - Base Exemptions)
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-2017-print.pdf#page=3
# NOTE: NBER's historical state tax forms archive has directory structure
# suggesting forms from 1990-2008 and 2020-2025, but only 3 forms
# actually exist on their server (2020-2022). NH DRA forms are available
# from 2017-2023. For forms prior to 2017, NH DRA requires direct contact
# (Forms@dra.nh.gov or 603-230-5001). RSA 77:5 sets exemptions at $2,400
# base and $1,200 additional (as of 2022) but historical amounts are not
# documented in current statutes. Following TAXSIM's implementation for
# pre-2017 values in the absence of other sources.
#
# Historical values sourced from TAXSIM 35 (http://taxsim.nber.org/taxsim35/):
# - 1977-1980: $600 single, $1,200 joint (TAXSIM source code lines 21267-21269)
# - 1981-1994: $1,200 single, $2,400 joint (TAXSIM source code lines 21265-21266)
# - 1995+: $2,400 single, $4,800 joint (TAXSIM source code lines 21263-21264)
SINGLE: 
  1977-01-01: 600
  1981-01-01: 1_200
  1995-01-01: 2_400
JOINT:
  1977-01-01: 1_200
  1981-01-01: 2_400
  1995-01-01: 4_800
SEPARATE:
  1977-01-01: 600
  1981-01-01: 1_200
  1995-01-01: 2_400
HEAD_OF_HOUSEHOLD: 
  1977-01-01: 600
  1981-01-01: 1_200
  1995-01-01: 2_400
SURVIVING_SPOUSE:
  1977-01-01: 600
  1981-01-01: 1_200
  1995-01-01: 2_400
