description: New Hampshire provides this base exemption based on filing status.
metadata:
  unit: currency-USD
  period: year
  breakdown:
  - filing_status
  label: New Hampshire base exemption amount
  reference: 
    - title: TECHNICAL INFORMATION RELEASE TIR 2025-001 I&D Tax Repealed Effective January 1, 2025
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/2025-001-technical-information-release-repeal.pdf
    - title: TITLE V - TAXATION - CHAPTER 77 - TAXATION OF INCOMES - Section 77:5
      href: https://www.gencourt.state.nh.us/rsa/html/V/77/77-5.htm
    - title: 2024 New Hampshire DP-10 Form Instructions
      href: https://www.revenue.nh.gov/sites/g/files/ehbemt736/files/documents/dp-10-instructions-2024.pdf#page=6
    - title: 2023 DP-10 Interest and Dividends Tax Return Instructions
      href: https://www.revenue.nh.gov/forms/2024/documents/dp-10-instructions-2023.pdf#page=6
    - title: 2022 DP-10 Interest and Dividends Tax Return Instructions
      href: https://www.revenue.nh.gov/forms/2023/documents/dp-10-instructions-2022.pdf#page=4
    - title: 2021 New Hampshire DP-10 Form
      href: https://www.revenue.nh.gov/forms/2022/documents/dp-10-2021-print.pdf#page=3
SINGLE: 
  2021-01-01: 2_400
JOINT:
  2021-01-01: 4_800
SEPARATE:
  2021-01-01: 2_400
HEAD_OF_HOUSEHOLD: 
  2021-01-01: 2_400
SURVIVING_SPOUSE:
  2021-01-01: 2_400
