description: Kansas provides the following exemption amount for each person in a filing unit.
values:
  2021-01-01: 2_250

metadata:
  period: year
  unit: currency-USD
  label: Kansas personal exemption
  reference:
  - title: 2021 Form K-40 instructions
    href: https://www.ksrevenue.gov/pdf/ip21.pdf#page=6
  - title: 2022 Form K-40 instructions
    href: https://www.ksrevenue.gov/pdf/ip22.pdf#page=6
  - title: 2023 Form K-40 instructions
    href: https://www.ksrevenue.gov/pdf/ip23.pdf#page=6
  - title: 2023 Form K-40 
    href: https://www.ksrevenue.gov/pdf/k-4023.pdf#page=1
  - title: KS Stat ยง 79-32,121 (2023) (a)
    href: https://law.justia.com/codes/kansas/chapter-79/article-32/section-79-32-121/
