description: Georgia uses this base amount for the standard of need under the Temporary Assistance for Needy Families program.

metadata:
  unit: currency-USD
  period: month
  breakdown:
    - range(1, 11)
  label: GA TANF standard of need base amount
  reference:
    - title: PAMMS TANF Policy Manual - Appendix A Financial Standards
      href: https://pamms.dhs.ga.gov/dfcs/tanf/appendix-a/
      publication_date: 2025-03-01
    - title: PAMMS TANF Policy Manual - Section 1525 Income
      href: https://pamms.dhs.ga.gov/dfcs/tanf/1525/

1:
  2025-03-01: 235
2:
  2025-03-01: 356
3:
  2025-03-01: 424
4:
  2025-03-01: 500
5:
  2025-03-01: 573
6:
  2025-03-01: 621
7:
  2025-03-01: 672
8:
  2025-03-01: 713
9:
  2025-03-01: 751
10:
  2025-03-01: 804
