description: Massachusetts provides the following Emergency Aid to the Elderly, Disabled and Children program standard assistance base amount, based on the living arrangement.
metadata:
  unit: currency-USD  
  period: month
  label: Massachusetts EAEDC standard assistance base amount
  breakdown:
    - ma_eaedc_living_arrangement 
  reference:
    - title: Emergency Aid to the Elderly Disabled and Children (EAEDC) Living Arrangement
      href: https://www.mass.gov/lists/emergency-aid-to-the-elderly-disabled-and-children-eaedc-living-arrangement
    - title: 106 CMR, ยง 704.435 - EAEDC Living Arrangement
      href: https://www.law.cornell.edu/regulations/massachusetts/106-CMR-704-435
    - title: Emergency Aid to the Elderly Disabled and Children (EAEDC) Grant Calculation
      href: https://www.mass.gov/lists/emergency-aid-to-the-elderly-disabled-and-children-eaedc-grant-calculation

A:
  2022-01-01: 401
B:
  2022-01-01: 121
C:
  2022-01-01: 72.8
D:
  2022-01-01: 401
E:
  2022-01-01: 72.8
F:
  2022-01-01: 258
H:
  2022-01-01: 267.3
NONE:
  2022-01-01: 0
