description: Arkansas provides this base personal tax credit amount.
values:
  2021-01-01: 29

metadata:
  unit: currency-USD
  period: year
  label: Arkansas personal tax credit base amount
  reference:
    - title: Arkansas 2022 Individual Income Tax Forms and Instructions, LINE 7A.
      href: https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/2022_AR1000F_and_AR1000NR_Instructions.pdf#page=12
    - title: 2022 AR1000F ARKANSAS INDIVIDUAL INCOME TAX RETURN Full Year Resident
      href: https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/2022_AR1000F_FullYearResidentIndividualIncomeTaxReturn.pdf#page=1
    - title: 2021 AR1000F ARKANSAS INDIVIDUAL INCOME TAX RETURN Full Year Resident
      href: https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/2021_AR1000F_FullYearResidentIndividualIncomeTaxReturn.pdf#page=1
    - title: 2023 AR1000F ARKANSAS INDIVIDUAL INCOME TAX RETURN Full Year Resident
      href: https://www.dfa.arkansas.gov/images/uploads/incomeTaxOffice/2023_AR1000F_FullYearResidentIndividualIncomeTaxReturn.pdf#page=1      
    # ยง 26-51-501(a)(1)(A) assigns the "adjusted individual credit".  
    # ยง 26-51-501(d)(1) assigns the $20 amount  
    # ยง 26-51-501(e) increases it with inflation relative to 2001 starting in 2003 
    - title: Ark. Code ยง 26-51-501 
      href: https://casetext.com/statute/arkansas-code-of-1987/title-26-taxation/subtitle-5-state-taxes/chapter-51-income-taxes/subchapter-5-tax-credits-generally/section-26-51-501-personal-tax-credits
