description: Minnesota adds these variables to federal adjusted gross income when computing its taxable income.
values:
  2021-01-01:
    - form_4972_lumpsum_distributions

metadata:
  unit: list
  period: year
  label: Minnesota additions to federal AGI
  reference:
  - title: 2021 Minnesota Schedule M1M, Income Additions and Subtractions, Page 3
    href: https://www.taxformfinder.org/forms/2021/2021-minnesota-form-m1m.pdf#page=3
  - title: 2022 Minnesota Schedule M1M, Income Additions and Subtractions, Page 3
    href: https://www.revenue.state.mn.us/sites/default/files/2024-01/m1m-22.pdf#page=3
  - title: 2023 Minnesota Schedule M1M, Income Additions and Subtractions, Page 3
    href: https://www.revenue.state.mn.us/sites/default/files/2023-12/m1m-23.pdf#page=3
  - title: 2024 Minnesota Schedule M1M, Income Additions and Subtractions, Page 3
    href: https://www.revenue.state.mn.us/sites/default/files/2024-12/m1m-24.pdf#page=3 
