description: Minnesota adds these variables to US AGI when computing its taxable income.
values:
  2021-01-01:
    - form_4972_lumpsum_distributions

metadata:
  unit: variable
  label: Minnesota additions to US AGI
  reference:
  - title: 2021 Minnesota Schedule M1M, Income Additions and Subtractions
    href: https://www.taxformfinder.org/forms/2021/2021-minnesota-form-m1m.pdf
  - title: 2022 Minnesota Schedule M1M, Income Additions and Subtractions
    href: https://www.revenue.state.mn.us/sites/default/files/2023-01/m1m_22.pdf
  - title: 2023 Minnesota Schedule M1M, Income Additions and Subtractions
    href: https://www.revenue.state.mn.us/sites/default/files/2023-12/m1m-23.pdf
