description: Alaska provides this amount as the base payment under the Alaska Temporary Assistance Program for one caretaker with one dependent child.

values:
  2021-01-01: 821

metadata:
  unit: currency-USD
  period: month
  label: Alaska ATAP one caretaker base payment amount
  reference:
    - title: 7 AAC 45.523(a)(1) - Maximum payment levels
      href: https://www.law.cornell.edu/regulations/alaska/7-AAC-45.523
    - title: AS 47.27.025(a) - Temporary Assistance Benefits
      href: https://www.akleg.gov/basis/statutes.asp#47.27.025
