description: Massachusetts counts these sources as countable assets under the Emergency Aid to the Elderly, Disabled and Children program. 
values:
  2022-01-01:
    - spm_unit_cash_assets
    - retirement_distributions
metadata:
  unit: list
  period: year 
  label: Massachusetts EAEDC assets sources
  reference:
    - title: 106 CMR 704.120 - Countable Assets
      href: https://www.law.cornell.edu/regulations/massachusetts/106-CMR-704-120
  
