#!/usr/bin/env python3
"""Final report on NH tax comparison with TAXSIM."""

print("NEW HAMPSHIRE TAX COMPARISON: PolicyEngine vs TAXSIM")
print("=" * 70)
print()

print("KEY FINDING: TAXSIM appears to have a bug in its NH tax calculation.")
print()

print("1. TAXSIM NH Exemption Formula (from source code):")
print("   For years >= 1995:")
print("     exemp = data(7)*2400 + (data(9)+data(10))*1200")
print("     where data(7) = number of tax units (1 single, 2 married)")
print("           data(9) = number of people age 65+")
print("           data(10) = related to blind/disabled")
print()

print("2. Expected vs Actual TAXSIM Exemptions:")
print()
print("   Year 2020 Expected:")
print("     Single: $2,400 base")
print("     Joint: $4,800 base")
print("     Age 65+: +$1,200 per person")
print()
print("   Year 2020 TAXSIM Actual:")
print("     Single (any age): $8,000")
print("     Joint (any age): $16,050")
print()

print("3. Analysis of TAXSIM Bug:")
print()
print("   For a single filer in 2020, TAXSIM shows $8,000 exemption")
print("   Using their formula: data(7)*2400 + (data(9)+data(10))*1200 = 8000")
print("   With data(7)=1: 2400 + (data(9)+data(10))*1200 = 8000")
print("   This means: (data(9)+data(10)) = 4.67")
print()
print("   This is impossible since these should be counts of people.")
print("   TAXSIM appears to be incorrectly calculating NH exemptions.")
print()

print("4. PolicyEngine Implementation:")
print()
print("   PolicyEngine correctly implements NH tax based on tax forms:")
print("   - Base exemptions: $2,400 single, $4,800 joint (2020)")
print("   - Additional exemptions: $1,200 for age 65+, blind, or disabled")
print("   - Tax rate: 5% on interest and dividends above exemptions")
print()

print("5. Comparison Table (2020):")
print()
print("   Scenario                  | TAXSIM Exemp | PE Exemp | TAXSIM Tax | PE Tax")
print("   " + "-" * 70)
print("   Single, $10k income       | $8,000       | $2,400   | $31.15     | $380.00")
print("   Joint, $5k income         | $16,050      | $4,800   | $0.00      | $10.00")
print("   Single 65+, $10k income   | $8,000       | $3,600   | $31.15     | $320.00")
print()

print("6. Conclusion:")
print()
print("   TAXSIM's NH tax calculation appears to be incorrect. It shows:")
print("   - Exemptions that don't match the tax forms")
print("   - No difference for taxpayers age 65+")
print("   - Tax amounts that are too low")
print()
print("   PolicyEngine's implementation matches the actual NH tax forms")
print("   and statutory requirements.")