description: Puerto Rico accounts for the following gross income sources.
values:
  2019-02-20:
    # salary/wages
    - irs_employment_income
    - self_employment_income
    - partnership_s_corp_income

    - taxable_retirement_distributions # distributions from retirement plans
    - capital_gains # sale or trade of capital assets
    - taxable_interest_income # interests
    - dividend_income # dividends 
    # distributions from gov plans
    # distributions from individual retirement, education accounts
    - taxable_pension_income # annuities, pensions
    - miscellaneous_income # other income 
    # profits from pass-through entities
    # Distributions from deferred compensation plans, partial/lump-sum distributions 
    # from qualified retirement plans, fixed/variable annuities not subject to preferential rate
    # income from salaries, wages etc. received by nonresident person
    - alimony_income # alimony received
    # distributions due to disaster declared by PR
    # gain or loss from manufacturing
    # gain or loss from sale of goods
    - farm_income # gain or loss from farming
    # gain or loss from services rendered
    - rental_income # gain or loss from rental business

    # profits from any source
    - taxable_unemployment_compensation
    - taxable_social_security
    - illicit_income
    - estate_income
    - debt_relief
metadata:
  unit: list
  period: year
  label: Puerto Rico gross income sources
  reference:
    - title: 
    - title: P.R. Laws tit. 13, ยง 30101 
      href: https://law.justia.com/codes/puerto-rico/title-thirteen/subtitle-17/part-ii/chapter-1005/subchapter-a/30101/
    - title: P.R. Individual Income Tax Return, Form 482
      href: https://hacienda.pr.gov/sites/default/files/individuals_2024_rev._jul_12_24_9-30-24_informative.pdf#page=2
