description: Puerto Rico gross income sources.
values:
  2019-02-20:
    # salary/wages
    - irs_employment_income
    - self_employment_income
    - partnership_s_corp_income
    - farm_income
    - farm_rent_income
    
    - taxable_pension_income # includes annuities & endowments
    - estate_income
    # trusts?

    # income from divorce?

    # cancellation of indebtedness
    - debt_relief

    # distributions from corporations?

    - rental_income
    # Royalties included in rental income
    - dividend_income
    - taxable_interest_income

    - capital_gains
    - taxable_unemployment_compensation
    - taxable_social_security
    - illicit_income
    - taxable_retirement_distributions
    - miscellaneous_income

metadata:
  unit: list
  period: year
  label: Gross income sources
  reference:
    - title: P.R. Laws tit. 13, ยง 30101 
      href: https://casetext.com/statute/laws-of-puerto-rico/title-thirteen-taxation-and-finance/subtitle-17-internal-revenue-code-of-2011/part-ii-income-taxes/chapter-1005-computation-of-taxable-income/subchapter-a-determination-of-net-income-general-concepts/30101-gross-income
