description: IRS multiplies the excess of the total and reduced itemized deductions by this rate.
values:
  2017-01-01: 0.8
metadata:
  unit: /1
  period: year
  label: IRS reduced itemized deductions base rate
  reference:
    - title: 26 U.S. Code ยง 68 - Overall limitation on itemized deductions, (a)(2) 
      href: https://www.law.cornell.edu/uscode/text/26/68
