description: Riverside county counts these sources as countable property under the General Relief Program.
values:
  2020-01-01:
    - spm_unit_cash_assets
    - ca_riv_general_relief_countable_vehicle_value
    - personal_property
    # - assessed_property_value

metadata:
  unit: list
  period: year
  label: Riverside County General Relief property
  reference: 
    - title: General Assistance Eligibility p.22
