description: DC adds these items to US AGI when computing DC AGI.
metadata:
  unit: list
  label: DC additions to US adjusted gross income
  reference:
    - title: Code of the District of Columbia § 47–1803.02. Gross income — Items included and excluded; "adjusted gross income" defined.
      href: https://code.dccouncil.gov/us/dc/council/code/sections/47-1803.02
    - title: 2021 Form D40 Booklet, Schedule I
      href: https://otr.cfo.dc.gov/sites/default/files/dc/sites/otr/publication/attachments/52926_D-40_12.21.21_Final_Rev011122.pdf#page=63
    - title: 2022 Form D40 Booklet, Schedule I
      href: https://otr.cfo.dc.gov/sites/default/files/dc/sites/otr/publication/attachments/2022_D-40_Booklet_Final_blk_01_23_23_Ordc.pdf#page=55
    - title: 2023 Form D40 Booklet, Schedule I
      href: https://otr.cfo.dc.gov/sites/default/files/dc/sites/otr/publication/attachments/2023_D40_Book_Final_012324.pdf#page=55
    - title: 2024 DC Form D-40 Booklet, Schedule I
      href: https://otr.cfo.dc.gov/sites/default/files/dc/sites/otr/publication/attachments/2024_D40_Booklet_011525.pdf#page=55
values:
  2021-01-01:
    - dc_self_employment_loss_addition
