description: Arizona limits income to this share of the federal poverty guideline under the Temporary Assistance for Needy Families program.

metadata:
  unit: /1
  period: year
  label: Arizona TANF income limit rate
  reference:
    - title: Arizona DES CNAP Manual FAA5.CA_Benefit_Determination - Needy Family Test
      href: https://dbmefaapolicy.azdes.gov/index.html#page/FAA5/CA_Benefit_Determination.html#wwpID0E0NQB0FA

values:
  2022-10-01: 1
