description: Oregon allows for the following retirement income credit base amount, based on filing status.
metadata:
  unit: currency-USD
  period: year
  breakdown:
    - filing_status 
  label: Oregon retirement income credit base
  reference:
    - title: Chapter 316 — Personal Income Tax 316.157 - Credit for retirement income (2)(d)(B)
      href: https://oregon.public.law/statutes/ors_316.157
    - title: 2022 Publication OR-17, Oregon Individual Income Tax Guide, 150-101-431
      href: https://www.oregon.gov/dor/forms/FormsPubs/publication-or-17_101-431_2022.pdf#page=109
    - title: 2023 Publication OR-17, Oregon Individual Income Tax Guide, 150-101-431
      href: https://www.oregon.gov/dor/forms/FormsPubs/publication-or-17_101-431_2023.pdf#page=109
    - title: 2024 Publication OR-17, Oregon Individual Income Tax Guide, 150-101-431
      href: https://www.oregon.gov/dor/forms/FormsPubs/publication-or-17_101-431_2024.pdf#page=106
      
JOINT:
  2018-01-01: 15_000
HEAD_OF_HOUSEHOLD:
  2018-01-01: 7_500
SURVIVING_SPOUSE:
  2018-01-01: 7_500
SINGLE:
  2018-01-01: 7_500
SEPARATE:
  2018-01-01: 7_500
