description: >-
  Income sources unconditionally excluded from TAFDC eligibility
  and grant calculations per 106 CMR 704.250. Does not include
  conditional exclusions (e.g. SSI recipients' other income,
  lump sum caps, child support pass-through) which require
  separate variable logic.
metadata:
  type: list
  period: month
  label: Massachusetts TAFDC noncountable income sources
  reference:
    - title: 106 CMR 704.250 - Noncountable Income
      href: https://www.law.cornell.edu/regulations/massachusetts/106-CMR-704-250
values:
  0001-01-01:
    # (C) SNAP benefits
    - snap
    # (D)+(F) School lunch subsidies
    - spm_unit_school_lunch_subsidy
    # (F) WIC
    - wic
    # (J) Financial aid (Pell Grants)
    - spm_unit_pell_grant
    # (S) Housing subsidies
    - spm_unit_capped_housing_subsidy
    # (BB) Home Energy Assistance Program
    - ma_liheap
