description: Wisconsin exemption includes this base amount.
metadata:
  period: year
  unit: currency-USD
  label: Wisconsin personal exemption base amount
  reference:
    - title: Legislative Fiscal Bureau paper on WI income tax 
      href: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2023/0002_individual_income_tax_informational_paper_2.pdf
    - title: 2023 Form 1 instructions
      href: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=16
    - title: 2024 Form 1 instructions
      href: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=15
values:
  2001-01-01: 700
