description: Nebraska limits the Child Care Subsidy program to children of this age or younger unless the child has a verified special need.
values:
  2020-09-15: 12

metadata:
  period: year
  unit: year
  label: Nebraska Child Care Subsidy base age limit
  reference:
    - title: 392 NAC 1-001.04(A)
      href: https://rules.nebraska.gov/api/fileStorage/GetAsByteArray/title-pdfs/Title_392.pdf/180#page=3
