description: Nebraska limits the child care subsidy to children of this age or younger, not requiring special needs care.  
values:
  2021-08-28: 12
metadata:
  period: year
  unit: year
  label: Nebraska child care subsidy base age threshold
  reference:
    - title: Nebraska DHHS, Child Care Subsidy Information For Parents
      href: https://dhhs.ne.gov/Pages/Child-Care-Subsidy-Information-for-Parents.aspx
