description: Alaska ATAP base payment amount for one caretaker with one dependent child.

values:
  2017-01-01: 821

metadata:
  unit: currency-USD
  period: month
  label: Alaska ATAP base payment amount
  reference:
    - title: 7 AAC 45.523(a)(1) - Maximum payment levels
      href: https://www.law.cornell.edu/regulations/alaska/7-AAC-45.523
    - title: Temporary Assistance Need and Maximum Payment Standards
      href: http://dpaweb.hss.state.ak.us/POLICY/PDF/TA-Standards.pdf#page=1
