name: Test
on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.13'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Install dependencies
        run: uv sync --dev
        
      - name: Turn off default branching
        shell: bash
        run: bash ./update_itemization.sh
        
      - name: Run non-structural YAML tests
        env:
          PYTHONUNBUFFERED: 1
        run: |
          echo "Running non-structural YAML tests..."
          uv run make test-yaml-no-structural
          
      - name: Run structural YAML tests
        env:
          PYTHONUNBUFFERED: 1
        run: |
          echo "Running structural YAML tests..."
          uv run make test-yaml-structural
          
      - name: Run Python-based tests
        env:
          PYTHONUNBUFFERED: 1
        run: |
          echo "Running Python-based tests..."
          uv run make test-other
